#!/bin/bash

# Guide de déploiement GitHub + Vercel pour Ramadan Reset

echo "🚀 Guide de déploiement - Ramadan Reset App"
echo "============================================"
echo ""

echo "📋 ÉTAPE 1 : Créer le repo sur GitHub"
echo "--------------------------------------"
echo "1. Allez sur https://github.com/new"
echo "2. Repository name: ramadan-reset"
echo "3. Description: Application mobile-first de suivi fitness Ramadan pour 40+"
echo "4. Public ou Private (au choix)"
echo "5. NE PAS cocher 'Add README' ni 'Add .gitignore'"
echo "6. Cliquez 'Create repository'"
echo ""

echo "📤 ÉTAPE 2 : Pousser le code"
echo "----------------------------"
echo "Remplacez VOTRE-USERNAME par votre nom d'utilisateur GitHub"
echo ""
echo "cd /Users/toufiq/Applications/antigravity\ perso/ramadan-reset"
echo ""
echo "# Ajouter le remote GitHub (remplacez VOTRE-USERNAME)"
echo "git remote add origin https://github.com/VOTRE-USERNAME/ramadan-reset.git"
echo ""
echo "# Pousser le code"
echo "git push -u origin main"
echo ""

echo "🌐 ÉTAPE 3 : Déployer sur Vercel"
echo "--------------------------------"
echo "1. Allez sur https://vercel.com/new"
echo "2. Cliquez 'Continue with GitHub'"
echo "3. Autorisez Vercel à accéder à vos repos"
echo "4. Sélectionnez 'ramadan-reset'"
echo "5. Cliquez 'Deploy'"
echo ""
echo "✅ C'est tout ! Vercel va builder et vous donner une URL"
echo ""

echo "⚠️  IMPORTANT : Si git push demande un mot de passe"
echo "---------------------------------------------------"
echo "GitHub n'accepte plus les mots de passe pour git push."
echo "Vous devez créer un Personal Access Token (PAT) :"
echo ""
echo "1. Allez sur https://github.com/settings/tokens"
echo "2. Cliquez 'Generate new token' → 'Generate new token (classic)'"
echo "3. Donnez un nom : 'Ramadan Reset Deploy'"
echo "4. Cochez 'repo' (accès complet aux repos)"
echo "5. Cliquez 'Generate token'"
echo "6. COPIEZ le token (vous ne le reverrez plus !)"
echo "7. Utilisez ce token comme mot de passe lors du git push"
echo ""

echo "🔧 Alternative : Utiliser SSH (plus simple à long terme)"
echo "--------------------------------------------------------"
echo "1. Générer une clé SSH :"
echo "   ssh-keygen -t ed25519 -C 'votre-email@example.com'"
echo ""
echo "2. Ajouter la clé à GitHub :"
echo "   cat ~/.ssh/id_ed25519.pub"
echo "   Copiez le résultat et ajoutez-le sur https://github.com/settings/keys"
echo ""
echo "3. Utiliser l'URL SSH au lieu de HTTPS :"
echo "   git remote set-url origin git@github.com:VOTRE-USERNAME/ramadan-reset.git"
echo "   git push -u origin main"
echo ""
